import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Glob('*.c')

group = DefineGroup('Command', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
