# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('nftl', src, depend = ['RT_USING_NFTL', 'RT_USING_DFS'], CPPPATH = CPPPATH)

Return('group')
